// packages/qiankun-demo/react-child/src/views/CssIsolation/index.tsx
import { Col, Row } from 'antd'
import styles from './index.module.less'

export default function CssIsolation() {
  return (
    <>
      <Row>
        <Col>
          <h2>react18子应用(CSS Module)</h2>
        </Col>
      </Row><Row>
        <Col span={12} className={styles.firstCol}>class="first-col"<br />background-color: purple;<br />font-size: 20px;</Col>
        <Col span={12} className={styles.secondCol}>class="second-col"<br />background-color: gray;<br />font-size: 20px;</Col>
      </Row>
    </>
  )
}

// packages/qiankun-demo/vue2-child/src/views/CssIsolation.vue
<template>
  <div>
    <a-row>
      <a-col><h2>Vue2子应用(style scope)</h2></a-col>
    </a-row>
    <a-row>
      <a-col :span="12" class="first-col">class="first-col"<br />background-color: blue;<br />font-size: 30px;</a-col>
      <a-col :span="12" class="second-col">
        class="second-col"<br />background-color: orange;<br />font-size: 30px;
      </a-col>
    </a-row>
  </div>
</template>

<script lang="ts">
import { Col, Row } from 'ant-design-vue'
export default {
  name: 'CssIsolation',
  components: {
    [Row.name]: Row,
    [Col.name]: Col,
  },
}
</script>

<style lang="less" scoped>
.first-col {
  color: #ffffff;
  background-color: blue;
  font-size: 30px;
}

.second-col {
  color: #ffffff;
  background-color: orange;
  font-size: 30px;
}
</style>
