// packages/garfish-demo/react-child/src/views/NavigateView/index.tsx
import { Button, Space, Typography } from 'antd'

export default function NavigateView() {
  const handleClick = ({ path, basename }: { path: string, basename: string }) => {
    window.Garfish.router?.push({
      path,
      basename,
    })
  }
  const buttons = [
    {
      path: '/main/communication-test',
      basename: '',
      label: '跳转至主应用 page1'
    },
    {
      path: '/communication-test',
      basename: '/vue2App',
      label: '跳转至Vue2子应用'
    },
    {
      path: '/communication-test',
      basename: '/reactApp',
      label: '跳转至React18子应用'
    },
    {
      path: '/communication-test',
      basename: '/viteApp',
      label: '跳转至Vite子应用'
    },
  ].map(item => (
    <Button type="primary" onClick={() => handleClick(item)} key={item.basename + item.path}>{item.label}</Button>
  ))

  return (
    <>
      <Typography.Title>React18子应用内控制跳转</Typography.Title>
      <Space size={20}>
        {buttons}
      </Space>
    </>
  )
}

// packages/garfish-demo/vue2-child/src/views/NavigateView.vue
<template>
  <div>
    <h1>Vue2子应用内控制跳转</h1>
    <a-space :size="20">
      <a-button type="primary" v-for="item in urls" :key="item.path" @click="handleClick(item)">
        {{ item.label }}
      </a-button>
    </a-space>
  </div>
</template>

<script lang="ts">
import { Space, Button } from 'ant-design-vue'

export default {
  name: 'NavigateView',
  data() {
    return {
      urls: [
        {
          label: '跳转至主应用 page1',
          basename: '/',
          path: '/main/communication-test',
        },
        {
          label: '跳转至Vue2子应用',
          basename: '/vue2App',
          path: '/communication-test',
        },
        {
          label: '跳转至React18子应用',
          basename: '/reactApp',
          path: '/communication-test',
        },
        {
          label: '跳转至Vite子应用',
          basename: '/viteApp',
          path: '/communication-test',
        },
      ],
    }
  },
  methods: {
    handleClick({ path, basename }: any) {
      console.log(path, basename)
      window.Garfish.router?.push({
        path,
        basename,
      })
    },
  },
  components: {
    [Space.name]: Space,
    [Button.name]: Button,
  },
}
</script>

<style lang="less" scoped>
h1 {
  font-size: 2em;
}
</style>
