// packages/icestark-demo/vue3-main/src/views/CommunicationTest.vue
<template>
  <a-space direction="vertical" class="box" :size="40">
    <a-divider>
      <a-typography-title>主应用页面</a-typography-title>
    </a-divider>
    <user-info />
    <a-divider>
      <a-typography-title :level="2">主应用消息</a-typography-title>
    </a-divider>
    <message-trigger />
    <a-divider>
      <a-typography-title :level="2">主应用Counter</a-typography-title>
    </a-divider>
    <counter />
  </a-space>
</template>

<script lang="ts">
export default {
  name: 'CommunicationTest'
}
</script>

<script lang="ts" setup></script>

<style lang="less" scoped>
.box {
  width: 100%;
}
</style>

// packages/garfish-demo/react-child/src/views/CommunicationTest/index.tsx
import { Divider, Space, Typography } from 'antd'
import UserInfo from '@/components/UserInfo'
import MessageTrigger from '@/components/MessageTrigger'
import Counter from '@/components/Counter'

export default function CommunicationTest() {
  return (
    <>
      <Space size={40} direction="vertical" style={{ width: '100%'}}>
        <Divider>
          <Typography.Title>React18子应用页面</Typography.Title>
        </Divider>
        <UserInfo />
        <Divider>
          <Typography.Title level={2}>React18子应用向主应用通信</Typography.Title>
        </Divider>
        <MessageTrigger />
        <Divider>
          <Typography.Title level={2}>React18子应用Counter</Typography.Title>
        </Divider>
        <Counter />
      </Space>
    </>
  )
}
